### ISSUE TITLE
Unable to resume after timeout

### ISSUE THREAD

**Issue by iHaagcom** [edgraaff/teams-chat-backup#22]
After downloading more than 1000 json files and 929 images I get the following error and the html file is not created.
Is there a way to create the index.html from what is currently downloaded? Can files also be downloaded?

downloading image-00928
downloading image-00929
Error: Request failed with status code 504
    at createError (C:\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\adapters\http.js:238:9)
    at RedirectableRequest.emit (node:events:527:28)
    at RedirectableRequest._processResponse (C:\teams-chat-backup-master\teams-chat-backup-master\node_modules\follow-redirects\index.js:346:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\teams-chat-backup-master\teams-chat-backup-master\node_modules\follow-redirects\index.js:57:10)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  config: {

**Comment by iHaagcom** [comment]
czerwony03 try addition solved the problem.
