### ISSUE TITLE
Error 400?

### ISSUE THREAD

**Issue by fablabnordvest** [edgraaff/teams-chat-backup#26]
Hi. Great tool if I could make it work :-)
I get this message. Any idea?

retrieve page 00000
Error: Request failed with status code 400
    at createError (C:\Users\RasmusGrusgaard\Downloads\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\RasmusGrusgaard\Downloads\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\RasmusGrusgaard\Downloads\teams-chat-backup-master\teams-chat-backup-master\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {

etc

**Comment by fablabnordvest** [comment]
Does it have anything to do wit https://learn.microsoft.com/en-us/graph/teams-licenses?
